import type { Metadata } from "next";
import "./globals.css";
import { Space_Grotesk, Raleway } from "next/font/google";
import { LoginContextProvider } from "@/backend/loginContext";
import { StudentContextProvider } from "@/backend/studentContext";
import { EventsContextProvider } from "@/backend/eventsContext";
import MasterLoader from "@/components/MasterLoader";

export const metadata: Metadata = {
  title: "FBLA Event Registration",
  description: "Generated by create next app",
  icons: {}
};


const space = Space_Grotesk({
  weight: ["300", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-space"
})

const raleway = Raleway({
  weight: ["300", "500", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-raleway"
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${space.variable} ${raleway.variable} antialiased`}
      >
        <LoginContextProvider>
          <StudentContextProvider>
            <EventsContextProvider>
              <MasterLoader>
                {children}
              </MasterLoader>
            </EventsContextProvider>
          </StudentContextProvider>
        </LoginContextProvider>
      </body>
    </html>
  );
}
